### ISSUE TITLE
To specific python version in installer.sh

### ISSUE THREAD

**Issue by eXeler0n** [JustTemmie/steam-presence#11]
Hey,

in the file installer.sh I had problems, because in line 65 the command is `python3.10 -m venv .`
This created errors on my machine as I have Python 3.11.3 installe, so python3.10 isn't working.

Changing the line to `python3 -m venv .` solved the problem and should be future proof (as long as 3 is the main version).

**Comment by miermontoto** [comment]
yesterday I created a pull request that fixes this issue: https://github.com/JustTemmie/steam-presence/pull/10

**Comment by JustTemmie** [comment]
fixed by #10
