### ISSUE TITLE
Add support for multiple accounts

### ISSUE THREAD

**Issue by TibixDev** [JustTemmie/steam-presence#12]
Hey, this would be a really useful feature for me as I have multiple Steam accounts and I sometimes switch between them.

The endpoint `http://api.steampowered.com/ISteamUser/GetPlayerSummaries/v0002/` mentions support for this:
```
steamids
    A comma-separated list of 64 bit IDs to retrieve profiles for.
```

**Comment by JustTemmie** [comment]
sure, i actually removed this just a couple days ago as i thought no one would be using it - i'll add it back within tomorrow

**Comment by TibixDev** [comment]
Thanks a bunch for the swift response and commit, I appreciate it. :)
