### ISSUE TITLE
Author's name coverImageText?

### ISSUE THREAD

**Issue by rusocop** [JustTemmie/steam-presence#17]
Im little confused, what library are you using to get author's name to put it on the cover image text? I wanted to change it to game's name but can't find the source. Thanks

**Comment by JustTemmie** [comment]
"Art by x on SteamGrid DB" is just given directly by the steam grid DB API, line 163 and 190.
if you have SGDB disabled, "gameName on steam" will be displayed instead, line 264

not entirely sure what part you're referring to, if it was the first one, change the two occurances `coverImageText = f"Art by {entry[4]} on SteamGrid` to `coverImageText = gameName`

**Comment by rusocop** [comment]
Sorry for not mentioning, the line were 163 and 190 indeed. My idea was changing the "Art by {entry[4]} on SteamGrid" to "[gameName] - Steam" (_or however it should be to display the game's name_)

**Comment by JustTemmie** [comment]
well you'd need to have a + between the strings so, `coverImageText = gameName + " - Steam"`
alternatively `coverImageText = f"{gameName}  - Steam"` would also work

**Comment by rusocop** [comment]
Thanks!
