### ISSUE TITLE
No longer detects non steam games

### ISSUE THREAD

**Issue by superboo07** [JustTemmie/steam-presence#19]
Apon running any non steam game the presense manager will not detect its use, even if it is ran through steam, and appears on the steam user profile.

**Comment by JustTemmie** [comment]
will look into, thanks for the issue

**Comment by JustTemmie** [comment]
sorry i never meant to close this, whoops - but, may i ask if you're getting any errors or anything?

![image](https://github.com/JustTemmie/steam-presence/assets/47639983/aed31eb3-72b0-43dd-846e-4d3a825d0de4)
it seems to work perfectly fine for me

**Comment by JustTemmie** [comment]
what exactly did you input as your steam id?

**Comment by superboo07** [comment]
hmm interestingly enough revoking and creating a new steam API key has fixed the issue

**Comment by superboo07** [comment]
> what exactly did you input as your steam id?

76561198304794149

**Comment by JustTemmie** [comment]
> hmm interestingly enough revoking and creating a new steam API key has fixed the issue

huh alright, that's interesting - suppose i should look into that
