### ISSUE TITLE
Icons.txt error

### ISSUE THREAD

**Issue by TheM1Stery** [JustTemmie/steam-presence#25]
Your code references path to /icons.txt but the file itself is in data/icons.txt. The scripts throws an error because of it.

**Comment by JustTemmie** [comment]
shit

**Comment by TheM1Stery** [comment]
> shit

Looks like there is a error(didn't change the path?) in the installer. I think it can be fixed by changing the path in python code or changing the path in the installer

**Comment by JustTemmie** [comment]
should be fixed now :p sorry for the error - i have no idea how i didn't encounter that in testing

**Comment by JustTemmie** [comment]
> > shit
> 
> Looks like there is a error(didn't change the path?) in the installer. I think it can be fixed by changing the path in python code or changing the path in the installer

yep, exactly that - was also happening with games.txt and customGameIDs.json

**Comment by JustTemmie** [comment]
ty for issue report though, wouldn't have known it was there myself :sweat_smile:
