### ISSUE TITLE
changing rich presence title?

### ISSUE THREAD

**Issue by shadowshard4080** [JustTemmie/steam-presence#36]
Is there any way we can change "a game on steam" to "on Steam Deck" so that it says
```
Playing on Steam Deck
Control Ultimate Edition
The Foundation
04:26 elapsed
```
instead of "Playing a game on steam, etc"
If that's possible I think it would look a lot better. I know this rich presence isn't intended solely for the Steam Deck but that's what I and many others are using it for, so the ability to customize the RPC title would be great

**Comment by JustTemmie** [comment]
this is actually a feature, the instructions can be found [here](https://github.com/JustTemmie/steam-presence#discord-application-id),  it's not trivial, but fairly easy to do

if you need any additional help feel free to ask

**Comment by shadowshard4080** [comment]
> this is actually a feature, the instructions can be found [here](https://github.com/JustTemmie/steam-presence#discord-application-id),  it's not trivial, but fairly easy to do
> 
> if you need any additional help feel free to ask

I do have another question.
How do I change the pop-up text for the rich presence icon from "<game> on steam" to "Playing on Steam Deck"?
I tried to change that in the main.py code, but it didn't seem to work. 🤔

**Comment by JustTemmie** [comment]
line 331
```py
respone = r.json()

coverImage = respone[str(gameSteamID)]["data"]["header_image"]
# change this
# set it to whatever you'd like, such as "Playing on Steam Deck" or f"Playing {gameName} on Steam Deck"
coverImageText = f"{gameName} on steam" or f"Playing {gameName} on Steam Deck"
# do note this is NOT saved to disk, just in case someone ever adds an entry to the SGDB later on

log(f"successfully found steam's icon for {gameName}")
```

**Comment by shadowshard4080** [comment]
Hmm, it didn't work before when I did just that.
However, when I ran the install script again, then it worked.
Thank you.

**Comment by JustTemmie** [comment]
alright cool lmao, no idea what happened
