### ISSUE TITLE
Unsupported os (opensuse tumbleweed)

### ISSUE THREAD

**Issue by pollux56** [JustTemmie/steam-presence#38]
when running the installer.sh it will spit out that opensuse isnt supported even tho its linux
no other errors appear 

This script is for Linux and macOS, and it's still in testing phases. If you encounter any bugs, please open an issue.
Press the enter key to continue...

Setting up virtual environment
mkdir: cannot create directory ‘venv’: File exists
Requirement already satisfied: pip in ./lib64/python3.11/site-packages (23.3.1)
Requirement already satisfied: wheel in ./lib64/python3.11/site-packages (0.42.0)
Requirement already satisfied: python-steamgriddb in ./lib64/python3.11/site-packages (from -r ../requirements.txt (line 1)) (1.0.5)
Requirement already satisfied: pypresence in ./lib64/python3.11/site-packages (from -r ../requirements.txt (line 2)) (4.3.0)
Requirement already satisfied: beautifulsoup4 in ./lib64/python3.11/site-packages (from -r ../requirements.txt (line 3)) (4.12.2)
Requirement already satisfied: requests in ./lib64/python3.11/site-packages (from -r ../requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: psutil in ./lib64/python3.11/site-packages (from -r ../requirements.txt (line 5)) (5.9.6)
Requirement already satisfied: soupsieve>1.2 in ./lib64/python3.11/site-packages (from beautifulsoup4->-r ../requirements.txt (line 3)) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib64/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib64/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib64/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./lib64/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (2023.11.17)

Testing if the script works

----------------------------------------------------------
[Dec 02 2023 - 22:52:41] progam's current folder structure version is up to date...
----------------------------------------------------------
[Dec 02 2023 - 22:52:41] loading config file
[Dec 02 2023 - 22:52:41] everything is ready!
----------------------------------------------------------
[Dec 02 2023 - 22:52:42] found game NARAKA: BLADEPOINT played by Pollux
Test might've worked, did it spit out any errors?
Commands executed.
Unsupported OS. This script is designed for Linux and macOS only.

**Comment by JustTemmie** [comment]
it looks like "$OSTYPE" isn't returning the expected "linux-gnu" string, sounds like some opensuse shenanigans oh well.

can you please run `"$OSTYPE"` in a terminal for me and reply with the message it returns so i can just fix the if-statement?
mine for example returns this
```
➜  ~ "$OSTYPE"
zsh: command not found: linux-gnu
```

**Comment by JustTemmie** [comment]
seems like opensuse tumbleweed just returns "linux" instead of the expected "linux-gnu"

i've gone ahead and updated the installer, just run `git pull` in the folder you downloaded the project in, and re-run the installer - it should hopefully work now

**Comment by pollux56** [comment]
Thank you  :D
