### ISSUE TITLE
RPC randomly disappears, not sure why?

### ISSUE THREAD

**Issue by anishgoyal1108** [JustTemmie/steam-presence#40]
[This](https://streamable.com/m20q38) video should sum things up quite well. No errors locally at all. Tried rebooting and reinstalling steam-presence. I am using the latest Discord from the AUR. I have sanity checked my json file multiple times, and it's accurate.

**Comment by JustTemmie** [comment]
this is weird, i don't believe it's a client side issue due to how RPC works on discord's end

does it actually disappear for your friends or is it just something that you think is happening to them, as it breaks in your own browser? i'm asking as it might be some weird caching with how discord works in the browser??

have you tried seeing it from a phone and checking how that functions?

**Comment by anishgoyal1108** [comment]
It shows the RPC when checking my account from my phone, but when I ask my friends, they say that they can't see anything.

**Comment by anishgoyal1108** [comment]
Alright, it was definitely a browser issue. Apparently, RPC isn't fully supported on the browser version of Discord, so it was my flawed checking that made me believe it didn't work. My friends were also trolling me so there's that.

**Comment by JustTemmie** [comment]
lmao - fair enough

**Comment by anishgoyal1108** [comment]
Wait I spoke too soon

**Comment by JustTemmie** [comment]
oh?

**Comment by anishgoyal1108** [comment]
It's visible on my phone but nobody else can see it

**Comment by anishgoyal1108** [comment]
and my friends said they're using the Discord application. they were able to see it for a split sec but then they couldnt any longer

**Comment by JustTemmie** [comment]
that's... strange? unsure what would be causing this, could you maybe try checking it from your phone on an alt account??

**Comment by JustTemmie** [comment]
alternatively try checking it with discord canary or something (their beta version)

**Comment by anishgoyal1108** [comment]
It doesn't show on an alt account from my phone. Trying canary now

**Comment by anishgoyal1108** [comment]
On canary: shows if I'm logged into my own account but doesn't show if viewing through an alt

**Comment by JustTemmie** [comment]
i'll have a look into it, i'll let you know if i can figure anything out

**Comment by anishgoyal1108** [comment]
OK Thanks!

**Comment by JustTemmie** [comment]
alright i can't seem to find out exactly what it is, the only thing i can possibly think of is if you've disabled people from seeing your statuses thru discord?

settings -> activity privacy -> display current activity as a status message
is this on or off?

**Comment by anishgoyal1108** [comment]
It's on. I'm reinstalling my operating system from scratch, so I'll let you know if it works after

**Comment by JustTemmie** [comment]
alright then

**Comment by anishgoyal1108** [comment]
It works now! Marking as resolved

**Comment by JustTemmie** [comment]
i assume you don't know what the issue might have been?

**Comment by anishgoyal1108** [comment]
nop
