### ISSUE TITLE
Unable to launch main.py

### ISSUE THREAD

**Issue by KikiLiyue** [JustTemmie/steam-presence#42]
When I try to launch Main.py through the terminal (Python3 main.py), I get the following error.
Traceback (most recent call last):
  File "/home/kiki/steam-presence/main.py", line 1147, in <module>
    main()
  File "/home/kiki/steam-presence/main.py", line 920, in main
    checkForUpdate()
  File "/home/kiki/steam-presence/main.py", line 902, in checkForUpdate
    if int(new) > int(old):
       ^^^^^^^^

I have tried to delete and git clone the folder to maybe fix it, but it ended not working
![Screenshot_20240103_224047](https://github.com/JustTemmie/steam-presence/assets/155606015/91444098-c2dd-42bc-94bc-1badc5ea7a59)

**Comment by JustTemmie** [comment]
i dont have time to look into it right now, for now you can remove the `checkforupdate()` function call or whatever it's called right under `main()`

**Comment by JustTemmie** [comment]
nvm i think i figured it out, i just fucked up the release version yesterday, just git pull it and it should be working

**Comment by JustTemmie** [comment]
actually you shouldnt have to git pull, it should just work
