### ISSUE TITLE
Running without Discord client

### ISSUE THREAD

**Issue by nfp0** [JustTemmie/steam-presence#44]
Is the Discord client running side by side with steam-presence a hard requirement?

You mentioned we can run steam-presence on a server (which I intended to do with Docker), but that would mean having a GUI running with Discord.

Can you please clarify how would such a setup be viable?
Are there tools that can send RPC data to Discord's servers other than the official client?

**Comment by JustTemmie** [comment]
there are technically others tools, the existing ones are all built into other discord clients though, mainly [arRPC](https://github.com/OpenAsar/arRPC), the dev of which has explicitly said is not something they're willing to help with [Running without any discord client](https://github.com/OpenAsar/arrpc/issues/24).

something you *can* do is installing x11 on the server, remoting into it, logging into discord, then setup a systemd service or something similar to run discord without a display. Though this would still take half a gig of ram or something similar, see [this](https://github.com/Radiicall/jellyfin-rpc/issues/80#issuecomment-1969562794) post if you want any more info on that

**Comment by JustTemmie** [comment]
feel free to re-open if you have any further questions
