### ISSUE TITLE
Additional Rich Presence data from games doesn't work

### ISSUE THREAD

**Issue by nezzled** [JustTemmie/steam-presence#45]
I did a normal install and followed all steps correctly, but it doesn't seem to show additional data from games that support it. I tested on ULTRAKILL and Bloons TD6, both of which behaved like other games and not like in screenshots. Code is unmodified (aside from a simple string change I did but that shouldn't affect anything) and the config looks totally fine.

[my_config.json](https://github.com/JustTemmie/steam-presence/files/14628685/my_config.json)

**Comment by JustTemmie** [comment]
can you send me some of the terminal output from it running?

**Comment by JustTemmie** [comment]
well, if you can't find your information [here](https://steamcommunity.com/miniprofile/911603854) whilst you're playing something such as bloons,it's likely an issue with your privacy settings within steam

**Comment by nezzled** [comment]
> well, if you can't find your information [here](https://steamcommunity.com/miniprofile/911603854) whilst you're playing something such as bloons,it's likely an issue with your privacy settings within steam
Ahh, I didn't know it fetched that info from Steam directly. In that case, I'll probably keep using IPC for games that support Rich Presence and this for the ones that don't. Thank you so much!

**Comment by JustTemmie** [comment]
:3
