### ISSUE TITLE
Discord shows up the normal RPC, but doesn't shows up the steam-presence RPC

### ISSUE THREAD

**Issue by thecubitoishere** [JustTemmie/steam-presence#46]
This is a question and also a problem i'm having with the script, i run the script but... im not sure what it's supposed to do next...
I have a config.json already set up with my steam id, user id, everything but... Is not showing up in my profile?

I have made sure that the script is running, changed the configs as i needed but nothing is working.

**Comment by JustTemmie** [comment]
may i get what the script is outputting to the terminal? you can blur names if you want to

`systemctl --user status steam-presence` if you installed it on linux

**Comment by thecubitoishere** [comment]
![image](https://github.com/JustTemmie/steam-presence/assets/120523653/63176813-f83a-4b76-a07c-42e71a36cdab)
it shows up but seems that is searching for a said "cookie.txt" file, which im honestly confused about it

**Comment by JustTemmie** [comment]
i assume you have "web_scrape" set to true in the config file then, as that requires your steam login cookie, try disabling it, seeing if that works

**Comment by thecubitoishere** [comment]
![image](https://github.com/JustTemmie/steam-presence/assets/120523653/cd0a437b-47fe-417a-b655-5a55bc968318)
The problem is that, "WEB_SCRAPE" it's already off

**Comment by JustTemmie** [comment]
be careful posting your steam api key :sweat_smile:

you might have to reload the script, unsure if it hot-reloads for web scraping, try resting it `systemctl --user restart steam-presence`

**Comment by thecubitoishere** [comment]
OOP
Sorry about that!
![image](https://github.com/JustTemmie/steam-presence/assets/120523653/7100a6d8-bfc2-4ccc-882e-e10d5e58a28c)
But it seems that its working now, the script at least... The problem is that the RPC is still not showing up
![image](https://github.com/JustTemmie/steam-presence/assets/120523653/4bb0d8dd-aa06-4ba2-b09a-23b9b15f4509)

**Comment by JustTemmie** [comment]
ah, it's because you have your activity set to private within steam, you'll have to change that to get it working

https://steamcommunity.com/my/edit/settings

i believe "Game details" must be set to public

**Comment by thecubitoishere** [comment]
![image](https://github.com/JustTemmie/steam-presence/assets/120523653/b5125606-3000-4d24-8450-1f88de64ae0d)
It worked! Thanks a lot!

**Comment by JustTemmie** [comment]
no worries, enjoy pizza tower!
