### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by MrHappyHam** [JustTemmie/steam-presence#47]
### Here's the error I got when running install.sh.
> Testing if the script works
> 
> [Apr 16 2024 - 17:55:28] couldn't find the the meta file, creating new one
> ----------------------------------------------------------
> [Apr 16 2024 - 17:55:28] updating meta.json's structure-version to `1`
> [Apr 16 2024 - 17:55:28] importing libraries for meta update
> [Apr 16 2024 - 17:55:28] creating /home/user1/Documents/scripts/steam-presence/./data/
> [Apr 16 2024 - 17:55:28] moving /home/user1/Documents/scripts/steam-presence/./icons.txt
> [Apr 16 2024 - 17:55:28] moving /home/user1/Documents/scripts/steam-presence/./games.txt
> [Apr 16 2024 - 17:55:28] moving /home/user1/Documents/scripts/steam-presence/./customGameIDs.json
> [Apr 16 2024 - 17:55:28] moving /home/user1/Documents/scripts/steam-presence/./meta.json
> ----------------------------------------------------------
> [Apr 16 2024 - 17:55:28] loading config file
> Traceback (most recent call last):
>   File "/home/user1/Documents/scripts/steam-presence/./main.py", line 1168, in <module>
>     main()
>   File "/home/user1/Documents/scripts/steam-presence/./main.py", line 977, in main
>     config = getConfigFile()
>              ^^^^^^^^^^^^^^^
>   File "/home/user1/Documents/scripts/steam-presence/./main.py", line 162, in getConfigFile
>     userSettings = json.load(f)
>                    ^^^^^^^^^^^^
>   File "/usr/lib/python3.11/json/__init__.py", line 293, in load
>     return loads(fp.read(),
>            ^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
>     obj, end = self.scan_once(s, idx)
>                ^^^^^^^^^^^^^^^^^^^^^^
> json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 1 (char 97)
> ./installer.sh: line 48: kill: (31841) - No such process
> Test might've worked, did it spit out any errors?
> Commands executed.
> Setting up service file for Linux
> Starting service
> If you encountered any errors with this script, please create an issue on the GitHub page
> 
> Script completed.

Any help is appreciated!

**Comment by JustTemmie** [comment]
it looks like you weren't in the same directory as the installer? try CDing into it

-------- Original Message --------

**Comment by MrHappyHam** [comment]
I was.
The first part of the output was

` ~/Documents/scripts/steam-presence/./installer.sh                                                                                                                                                                                  ✔ 
This script is for Linux and macOS, and it's still in testing phases. If you encounter any bugs, please open an issue.
Press the enter key to continue...

creating games.txt
creating icons.txt
creating customGameIDs.json
Setting up virtual environment
mkdir: cannot create directory ‘venv’: File exists
Requirement already satisfied: pip in ./lib/python3.11/site-packages (24.0)
Requirement already satisfied: wheel in ./lib/python3.11/site-packages (0.43.0)
Requirement already satisfied: python-steamgriddb in ./lib/python3.11/site-packages (from -r ../requirements.txt (line 1)) (1.0.5)
Requirement already satisfied: pypresence in ./lib/python3.11/site-packages (from -r ../requirements.txt (line 2)) (4.3.0)
Requirement already satisfied: beautifulsoup4 in ./lib/python3.11/site-packages (from -r ../requirements.txt (line 3)) (4.12.3)
Requirement already satisfied: requests in ./lib/python3.11/site-packages (from -r ../requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: psutil in ./lib/python3.11/site-packages (from -r ../requirements.txt (line 5)) (5.9.8)
Requirement already satisfied: soupsieve>1.2 in ./lib/python3.11/site-packages (from beautifulsoup4->-r ../requirements.txt (line 3)) (2.5)
Requirement already satisfied: charset-normalizer<4,>=2 in ./lib/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in ./lib/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./lib/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (2.2.1)
Requirement already satisfied: certifi>=2017.4.17 in ./lib/python3.11/site-packages (from requests->-r ../requirements.txt (line 4)) (2024.2.2)

Testing if the script works
`

**Comment by JustTemmie** [comment]
okay it seemed to have fucked up when it was trying to read the config, is your config file valid json?

**Comment by MrHappyHam** [comment]
Ah, if those errors mean there was a JSON validation issue, I can look into
that. I'll update you if that's the issue. TY

**Comment by MrHappyHam** [comment]
Forgot to mention, that was it. Much appreciated!
