### ISSUE TITLE
Adding custom games

### ISSUE THREAD

**Issue by alba4k** [JustTemmie/steam-presence#5]
In the old version (which was great, it's the only thing of it's kind that worked for me!), I didn't manage to get this working.

![immagine](https://user-images.githubusercontent.com/84153269/211194152-2aafb437-1706-407d-a3e6-8daa7be7cee5.png)

In the new version (which is even greater! thanks a lot for your work!) I'm even more confused on how the CUSTOM_GAME_OVERWRITE section is supposed to work. I'm not sure if I understood that correctly, how am I supposed to get a custom "game" (code-oss) or any process at all to show up with a name-icon pair (VSCode and ideally the image found [here](https://code.visualstudio.com/assets/images/code-stable.png))?

Again, thanks A LOT for your efforts on this process!

Also, I would suggest recreating an install.sh script that installs the systemd service, since that would make everything much easier and automatically set the correct file paths. I can write this if you'd like it :)

**Comment by JustTemmie** [comment]
so the "CUSTOM_GAME_OVERWRITE" section doesn't detect anything running locally, it's more just you can manually set the script to any game you want. the script can't actually detect anything running locally, though that is something i want to look into in the future

in addition games.txt isn't something the script has ever used and that config file is nothing like what this script uses, wrong format and everything :p


as for the install script, i actually wrote one the other day i just forgot to push it - unsure about how well it works. I'll go ahead and push it, if you want to test it go ahead, all pull request are welcome no matter how much you change 


P.S you should probably regenerate your steam grid and steam api keys since they're leaked in the screenshot :p

**Comment by alba4k** [comment]
Thanks, regenereted every key. :)

Also, that's interesting. After looking after it, I found what those old config files are! They're from [this](https://github.com/Radiicall/steam-presence-rust)other project, which happens to have the same name! huh. One more reason I probably confused the two. 

I'm guessing you probably know the owner, since in their readme they state `or use Temmie's "869994714093465680"` when talking about the application ID! Maybe just a "I do it in Python, you go with Rust" challenge?

This is also why I tought external processes were supported, and where the games.txt came from.
![immagine](https://user-images.githubusercontent.com/84153269/211431081-3a6022bf-a3ea-416c-8a25-553583e45bbe.png)

I think I will keep using your version of this going since I prefer the configuration method (python's json library is great!) 

In case you care, here is my 2am-written install script. Yours looks better for sure! ahah

```bash
#!/bin/bash

echo -e "\e[33m>>\e[0m Installing necessary python dependencies"
if python3 -m pip install -r requirements.txt; then
    echo -e "\e[32m>>\e[0m Success!\n"
fi

mkdir -p ~/.config/steam-presence

if cp --backup config.json icons.txt main.py ~/.config/steam-presence; then
    echo -e "\e[32m>>\e[0m Copied your configuration to $HOME/.config/steam-presence!"
fi

if echo "[Unit]
Description=Discord rich presence from Steam on Linux
Documentation=https://github.com/JustTemmie/steam-presence

[Service]
ExecStart=/home/$(whoami)/.config/steam-presence/steam-presence/main.py
Type=simple
Nice=19
SuccessExitStatus=130
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/home/$(whoami)/.config/steam-presence/steam-presence

[Install]
WantedBy=default.target" > ~/.config/systemd/user/steam-presence.service
then
    echo -e "\e[32m>>\e[0m Created a systemd service in $HOME/.config/systemd/user/steam-presence.service!"
    if systemctl --user enable --now ~/.config/systemd/user/steam-presence.service
    then
        echo -e "\e[32m>>\e[0m Enabled and started the systemd service!"
    fi
fi
```

You forgot to push yours, and I forgot to open a pull request for mine. Seems fair to me, ahah

**Comment by Radiicall** [comment]
We do know each other but I just wanted something for myself that doesnt use as many resources as python, also i just love writing in rust haha.

**Comment by alba4k** [comment]
I still can't get over its syntax :P

**Comment by JustTemmie** [comment]
> I still can't get over its syntax :P

exactly which part?

**Comment by JustTemmie** [comment]
p.s i just added support for locally running games, it's explained fairly alright in the latest release https://github.com/JustTemmie/steam-presence/releases/tag/v1.6 if that helps you out

**Comment by alba4k** [comment]
> > I still can't get over its syntax :P
> 
> exactly which part?

@JustTemmie I was referring to rust in general, nothing related to your program, which has a great source! 

I love how you use comments to explain the content. I basically use mine to ashame myself or the user
