### ISSUE TITLE
No module named 'pypresence'

### ISSUE THREAD

**Issue by xxxtrashcion** [JustTemmie/steam-presence#53]
Traceback (most recent call last):
  File "/home/xxxtrashcion/steam-presence/./main.py", line 23, in <module>
    from pypresence import Presence
ModuleNotFoundError: No module named 'pypresence'

Running the 'main.py' from the same folder as the 'installer.sh.' What am I doing wrong? Doesn't seem like it's running at startup on my arch setup.

**Comment by JustTemmie** [comment]
you have to use the provided virtual environment since you can't install packages with pip globally

tl;dr `./venv/bin/python main.py` instead of `python main.py`

**Comment by JustTemmie** [comment]
actually it's probably because python updated recently, nuking virtual environments in the process - so you'll have to delete your venv folder and rerun the installer

**Comment by xxxtrashcion** [comment]
> actually it's probably because python updated recently, nuking virtual environments in the process - so you'll have to delete your venv folder and rerun the installer

This solved the issue.
