### ISSUE TITLE
non-steam game whitelist?

### ISSUE THREAD

**Issue by pparmy** [JustTemmie/steam-presence#55]
,,  was curious about this with Minecraft in specific since it has native rich presence to begin with - and I assume if I launched through something like Prism for ex. I could simply leave the name as "Minecraft" and discord's native icons could be pulled
-though I'm not sure if there are more complexities to it more than that

**Comment by JustTemmie** [comment]
yea in theory you should be able to add minecraft to the local game list, i know on linux prism launcher identifies as "prismrun" but it should just work

**Comment by pparmy** [comment]
would this given I'm using a different device to host the steam-presence script?  'using my windows laptop in specific

**Comment by JustTemmie** [comment]
that wouldn't work, as there's no way for the program to know what you have open on your other device, you CAN add minecraft to steam as a non-steam game, then give steam presence your steam cookies and it can kinda scuffely display your presence
