### ISSUE TITLE
Rich Prescence updates very slowly

### ISSUE THREAD

**Issue by LunRos** [JustTemmie/steam-presence#57]
I don't know if this is a bug, or just something to do with the way steam-presence interacts with the Steam API, but I've been seeing very slow updates for the Steam Rich Presence feature.

Here's a screenshot from the console, I am using Windows 11, with Python 3.12.3 installed.
It takes about 30 mins for it to realize I'm in the menus, even though I was in the menu long before.
![image](https://github.com/JustTemmie/steam-presence/assets/33793109/387cdb5e-6c40-4829-83a6-cc26a3fd62b0)

Am wondering if there is a way to manually update the time it takes to update the presence.

**Comment by JustTemmie** [comment]
this is sadly just a problem on steam's end, but i'm looking thru options that should hopefully improve the situation

**Comment by LunRos** [comment]
Understandable, thx for the update.
