### ISSUE TITLE
Add short warning "Requires verified Steam account" and "Online status on Friend/Chat"

### ISSUE THREAD

**Issue by nattadasu** [JustTemmie/steam-presence#6]
As explained in the title, please add texts in README if the script required you to have verified account to get API key and Online status to allow the script to get your currently playing game.

This is because steam by default [restrict web api portal to be accessed by unverified account][support].

[![image](https://user-images.githubusercontent.com/49780229/212920840-fc448e9c-cc9d-4de7-8169-7f430fc7f2d1.png)][support]

[support]: https://help.steampowered.com/en/faqs/view/71D3-35C2-AD96-AA3A

**Comment by JustTemmie** [comment]
yeah sure
