### ISSUE TITLE
Syntax error in script

### ISSUE THREAD

**Issue by Splatube** [JustTemmie/steam-presence#61]
On lines 703 and 704 in main.py there are double quotes inside of an f-string which causes a syntax error. "icon" and "name" need to be replaced with 'icon' and 'name'.

**From**
> coverImage = f"https://<i></i>cdn.discordapp.com/app-icons/{appID}/{respone[**"icon"**]}.webp"
> coverImageText = f"{respone[**"name"**]}"

**To**
> coverImage = f"https://<i></i>cdn.discordapp.com/app-icons/{appID}/{respone[**'icon'**]}.webp"
> coverImageText = f"{respone[**'name'**]}"

**Comment by erenfro** [comment]
I put in a PR on this exact issue, actually. #62

**Comment by JustTemmie** [comment]
merged #62
