### ISSUE TITLE
'Fetch Steam Rich Presence' fetching is slow

### ISSUE THREAD

**Issue by SA64BD** [JustTemmie/steam-presence#71]
everything works fine with overwatch 2, except where fetching the presence details a very long time to refresh, so if I'm in a menu, rich presence still shows i'm in game even though my game is finished several minutes ago. There is no manual way to refresh the rich presence detail or no custom way to set intervals of when to refresh details. Any way to fix this slow fetching issue?

**Comment by JustTemmie** [comment]
nope, this is a steam limitation - steam presence will try refetch data every 20 seconds no matter what
