### ISSUE TITLE
Others can't see

### ISSUE THREAD

**Issue by DarkAssassin-DA** [JustTemmie/steam-presence#72]
hello! just wanted to say it's an amazing script. but my problem is, I can see rich presence but others can't

**Comment by DarkAssassin-DA** [comment]
nvm! only GOW 2018 has the problem

**Comment by JustTemmie** [comment]
probably just some discord privacy settings, in-case anyone runs into this you can change who can and who can't see your  activity status - you can change it in discord's settings, then under activity privacy where you'll find this

![screenshot-2024-11-21-20-53-29](https://github.com/user-attachments/assets/cc9677ee-d75e-4793-8746-6046b396f4a0)

you can also change it per server under settings, privacy & safety, server settings

![screenshot-2024-11-21-20-54-19](https://github.com/user-attachments/assets/b4e8f742-2bb4-41de-93b0-d1e8c1109842)
