### ISSUE TITLE
Service fails to run due to being saved in Kate

### ISSUE THREAD

**Issue by celestial-tenacity** [JustTemmie/steam-presence#73]
Hello!! I've come across this project and I gotta say I really love the work 💜
I have configured `config.json`, `customGameIDs.json` and `games.txt` using the Kate software, then gave the script a run after configuration, but ended up running into a repeating error.

```
deck@steamdeck ~/steam-presence (main) [1]> ./bin/python ./main.py
----------------------------------------------------------
[Nov 18 2024 - 23:11:17] progam's current folder structure version is up to date...
----------------------------------------------------------
[Nov 18 2024 - 23:11:17] loading config file
[Nov 18 2024 - 23:11:17] everything is ready!
----------------------------------------------------------
[Nov 18 2024 - 23:11:18] found game Undertale played by nemmy
[Nov 18 2024 - 23:11:23] steam app ID 391540 found for Undertale
[Nov 18 2024 - 23:11:23] game changed, updating to 'Undertale'
[Nov 18 2024 - 23:11:23] fetching the Discord game ID for Undertale
Traceback (most recent call last):
  File "/home/deck/steam-presence/./main.py", line 1205, in <module>
    main()
  File "/home/deck/steam-presence/./main.py", line 1173, in main
    getGameDiscordID()
  File "/home/deck/steam-presence/./main.py", line 638, in getGameDiscordID
    gameIDsFile = json.load(f)
                  ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 2)

```

Fortunately after awhile, I found issue https://github.com/JustTemmie/steam-presence/issues/27, so I tried wiping `./steam-presence/data` to see if the error was there, and the script started working like normal.

However, I have configured my `config.json` using Kate, and I have had no errors regarding such file (unlike in the issue I mentioned), so I figured either _just_ `config.json` itself was fixed in a patch for steam-presence.. or, it's an inconsistent bug? Anyway, I thought that maybe a warning could be used in the README against the usage of Kate would, be really helpful ;D _(I only recommend this as I do not wish to just simply report a bug that has already been reported.)_
I'm not smart enough to understand why this happens with Kate, but regardless I do hope this helps!!

**Comment by JustTemmie** [comment]
that is, strange?

Kate shouldn't make the file unreadable in any way as it's just a text file

not to sound accusatory but what likely happened is that you simply left a trailing comma or something somewhere and Kate just didn't warn you, JSON tends to be extremely finicky so I wouldn't be that surprised at all, I've done it countless times 

if you run into the issue again just create another issue with your customGameIDs.json file included so I can double check it's doing what I think it's doing

but thanks for the heads up!
