### ISSUE TITLE
Question (Not Issue)

### ISSUE THREAD

**Issue by corvock** [JustTemmie/steam-presence#75]
Didn't see it addressed, but wanted to find out what happens when i stop playing. So if i set this up on a server and start playing on my steam deck, it'll change discord presence. What I am looking for but when i end a gaming session does it clear out the Discord side?

**Comment by JustTemmie** [comment]
yea it does

Sent from Proton Mail Android

-------- Original Message --------

**Comment by corvock** [comment]
Awesome! tyvm!
